### ISSUE TITLE
Up on closing the jetcd client, observer stream used as part of keepAlive API  is still receiving events. 

### ISSUE THREAD

**Issue by KuZon** [etcd-io/jetcd#1132] opened 2023-03-24 18:33 UTC
**Versions**
- etcd: 3.5.9
- jetcd: 0.7.3
- java: Corretto-11.0.18.10.1

**Describe the bug**
Up on closing the jetcd client, observer stream used as part of keepAlive API  is still receiving events. 

**To Reproduce**
Close the client without running the close on ClosableClient returned by keepAlive API. Add some logs in ObservableStream used in keepAlive API. We can observe that we keep getting closed client error logs on the ObservableStream object.  

**Expected behavior**
The expected behaviour is to have all the observable streams associated with client close as we have closed that client it self.

**Comment by lburgazzoli** [comment] 2023-03-27 07:05
@KuZon do you have any time to work on a PR ?

**Comment by KuZon** [comment] 2023-03-27 09:14
Yes, please guide. I can spend some time.

**Comment by KuZon** [comment] 2023-04-20 05:03
@lburgazzoli any update on this ?

**Comment by lburgazzoli** [comment] 2023-04-20 05:54
No sorry, I don't have much time at this stage. A PR would be much than welcome

**Comment by lburgazzoli** [comment] 2023-06-09 20:09
@KuZon any change to have a PR with an integration test ?

**Comment by lburgazzoli** [comment] 2023-06-10 10:17
@KuZon I did try to reproduce thew issue and what I have noticed is that the observer's `onError` is invoked once with the message `Lease Client has been closed` which is expected as it is a way to notify the caller that the client has been closed, do you see any different behavior ?

**Comment by lburgazzoli** [comment] 2023-07-06 18:32
@KuZon any update ?

**Comment by lburgazzoli** [comment] 2023-08-07 18:09
No feedback since 1 month, closing it

**Closed by lburgazzoli** 2023-08-07 18:09 UTC
Labels: waiting-for-feedback
